name: dnsmon-go
on:
  push:
    paths-ignore:
    - ".github/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Download go modules
      run: go mod download

    - name: Verify go modules
      run: go mod verify

    - name: Build
      run: go build -v .
